// tslint:disable-next-line: no-namespace
namespace GameResources {

  export enum Mineral {
    UTRIUM = RESOURCE_UTRIUM as any,
    LEMERGIUM = RESOURCE_LEMERGIUM as any,
    KEANIUM = RESOURCE_KEANIUM as any,
    ZYNTHIUM = RESOURCE_ZYNTHIUM as any,
    OXYGEN = RESOURCE_OXYGEN as any,
    HYDROGEN = RESOURCE_HYDROGEN as any,
    CATALYST = RESOURCE_CATALYST as any,
  }


  export enum MineralCompoundBase {
    HYDROXIDE = RESOURCE_HYDROXIDE as any,
    ZYNTHIUM_KEANITE = RESOURCE_ZYNTHIUM_KEANITE as any,
    UTRIUM_LEMERGITE = RESOURCE_UTRIUM_LEMERGITE as any,
    GHODIUM = RESOURCE_GHODIUM as any
  }

  export enum MineralBoost {
    UTRIUM_HYDRIDE = RESOURCE_UTRIUM_HYDRIDE as any,
    UTRIUM_OXIDE = RESOURCE_UTRIUM_OXIDE as any,
    KEANIUM_HYDRIDE = RESOURCE_KEANIUM_HYDRIDE as any,
    KEANIUM_OXIDE = RESOURCE_KEANIUM_OXIDE as any,
    LEMERGIUM_HYDRIDE = RESOURCE_LEMERGIUM_HYDRIDE as any,
    LEMERGIUM_OXIDE = RESOURCE_LEMERGIUM_OXIDE as any,
    ZYNTHIUM_HYDRIDE = RESOURCE_ZYNTHIUM_HYDRIDE as any,
    ZYNTHIUM_OXIDE = RESOURCE_ZYNTHIUM_OXIDE as any,
    GHODIUM_HYDRIDE = RESOURCE_GHODIUM_HYDRIDE as any,
    GHODIUM_OXIDE = RESOURCE_GHODIUM_OXIDE as any,
    UTRIUM_ACID = RESOURCE_UTRIUM_ACID as any,
    UTRIUM_ALKALIDE = RESOURCE_UTRIUM_ALKALIDE as any,
    KEANIUM_ACID = RESOURCE_KEANIUM_ACID as any,
    KEANIUM_ALKALIDE = RESOURCE_KEANIUM_ALKALIDE as any,
    LEMERGIUM_ACID = RESOURCE_LEMERGIUM_ACID as any,
    LEMERGIUM_ALKALIDE = RESOURCE_LEMERGIUM_ALKALIDE as any,
    ZYNTHIUM_ACID = RESOURCE_ZYNTHIUM_ACID as any,
    ZYNTHIUM_ALKALIDE = RESOURCE_ZYNTHIUM_ALKALIDE as any,
    GHODIUM_ACID = RESOURCE_GHODIUM_ACID as any,
    GHODIUM_ALKALIDE = RESOURCE_GHODIUM_ALKALIDE as any,
    CATALYZED_UTRIUM_ACID = RESOURCE_CATALYZED_UTRIUM_ACID as any,
    CATALYZED_UTRIUM_ALKALIDE = RESOURCE_CATALYZED_UTRIUM_ALKALIDE as any,
    CATALYZED_KEANIUM_ACID = RESOURCE_CATALYZED_KEANIUM_ACID as any,
    CATALYZED_KEANIUM_ALKALIDE = RESOURCE_CATALYZED_KEANIUM_ALKALIDE as any,
    CATALYZED_LEMERGIUM_ACID = RESOURCE_CATALYZED_LEMERGIUM_ACID as any,
    CATALYZED_LEMERGIUM_ALKALIDE = RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE as any,
    CATALYZED_ZYNTHIUM_ACID = RESOURCE_CATALYZED_ZYNTHIUM_ACID as any,
    CATALYZED_ZYNTHIUM_ALKALIDE = RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE as any,
    CATALYZED_GHODIUM_ACID = RESOURCE_CATALYZED_GHODIUM_ACID as any,
    CATALYZED_GHODIUM_ALKALIDE = RESOURCE_CATALYZED_GHODIUM_ALKALIDE as any
  }

  export enum Commodity {
    UTRIUM_BAR = RESOURCE_UTRIUM_BAR as any,
    LEMERGIUM_BAR = RESOURCE_LEMERGIUM_BAR as any,
    ZYNTHIUM_BAR = RESOURCE_ZYNTHIUM_BAR as any,
    KEANIUM_BAR = RESOURCE_KEANIUM_BAR as any,
    GHODIUM_MELT = RESOURCE_GHODIUM_MELT as any,
    OXIDANT = RESOURCE_OXIDANT as any,
    REDUCTANT = RESOURCE_REDUCTANT as any,
    PURIFIER = RESOURCE_PURIFIER as any,
    BATTERY = RESOURCE_BATTERY as any,
    COMPOSITE = RESOURCE_COMPOSITE as any,
    CRYSTAL = RESOURCE_CRYSTAL as any,
    LIQUID = RESOURCE_LIQUID as any,
    WIRE = RESOURCE_WIRE as any,
    SWITCH = RESOURCE_SWITCH as any,
    TRANSISTOR = RESOURCE_TRANSISTOR as any,
    MICROCHIP = RESOURCE_MICROCHIP as any,
    CIRCUIT = RESOURCE_CIRCUIT as any,
    DEVICE = RESOURCE_DEVICE as any,
    CELL = RESOURCE_CELL as any,
    PHLEGM = RESOURCE_PHLEGM as any,
    TISSUE = RESOURCE_TISSUE as any,
    MUSCLE = RESOURCE_MUSCLE as any,
    ORGANOID = RESOURCE_ORGANOID as any,
    ORGANISM = RESOURCE_ORGANISM as any,
    ALLOY = RESOURCE_ALLOY as any,
    TUBE = RESOURCE_TUBE as any,
    FIXTURES = RESOURCE_FIXTURES as any,
    FRAME = RESOURCE_FRAME as any,
    HYDRAULICS = RESOURCE_HYDRAULICS as any,
    MACHINE = RESOURCE_MACHINE as any,
    CONDENSATE = RESOURCE_CONDENSATE as any,
    CONCENTRATE = RESOURCE_CONCENTRATE as any,
    EXTRACT = RESOURCE_EXTRACT as any,
    SPIRIT = RESOURCE_SPIRIT as any,
    EMANATION = RESOURCE_EMANATION as any,
    ESSENCE = RESOURCE_ESSENCE as any
  }

  export enum ResourceDeposit {
    MIST = RESOURCE_MIST as any,
    BIOMASS = RESOURCE_BIOMASS as any,
    METAL = RESOURCE_METAL as any,
    SILICON = RESOURCE_SILICON as any
  }

  export enum Resource {
    ENERGY = RESOURCE_ENERGY as any,
    POWER = RESOURCE_POWER as any,
    OPS = RESOURCE_OPS as any,
  }
}
